# Generated by Django 3.1 on 2020-09-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commentconnector',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='shareconnector',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='commentconnector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweets/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='HashtagConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_connector_hashtag', to='tweet.hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_connector_tweet', to='tweet.tweet')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(related_name='related_hashtags', through='tweet.HashtagConnector', to='tweet.Tweet'),
        ),
    ]
