# Generated by Django 3.1 on 2020-09-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20200924_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='most_popular_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_popular_hashtag', to='tweet.tweet'),
        ),
    ]
