# Generated by Django 3.1 on 2020-08-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_tweet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashtagConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_connector_hashtag', to='tweet.hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_connector_tweet', to='tweet.tweet')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(related_name='related_hashtags', through='tweet.HashtagConnector', to='tweet.Tweet'),
        ),
    ]
