# Generated by Django 3.1 on 2020-09-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20200831_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentconnector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
