# Generated by Django 3.1 on 2020-09-24 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_userhashtagtrends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhashtagtrends',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_trends', to=settings.AUTH_USER_MODEL),
        ),
    ]
